package JavaCourseworkUP847948;

public class EditOrderFrame extends javax.swing.JFrame {

    private Order order; 
    private int pos;
    
    public EditOrderFrame(Order order) {
        this.order = order;
        this.pos = 0;
        initComponents();
        jTextArea1.setText((order.getPizza(pos).getInvoice()));
        updateBoxes();
        Counter.setText(String.valueOf(this.pos+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PrevPizzaButton = new javax.swing.JButton();
        NextPizzaButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SizeComboBox1 = new javax.swing.JComboBox<>();
        CrustComboBox = new javax.swing.JComboBox<>();
        SauceComboBox = new javax.swing.JComboBox<>();
        T1ComboBox = new javax.swing.JComboBox<>();
        T2ComboBox = new javax.swing.JComboBox<>();
        Counter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PrevPizzaButton.setText("<");
        PrevPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevPizzaButtonActionPerformed(evt);
            }
        });

        NextPizzaButton.setText(">");
        NextPizzaButton.setToolTipText("");
        NextPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextPizzaButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete Pizza");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        OkButton.setText("Ok");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Size:");

        jLabel2.setText("Crust:");

        jLabel3.setText("Sauce:");

        jLabel4.setText("Topping 1:");

        jLabel5.setText("Topping 2:");

        SizeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        SizeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeComboBox1ActionPerformed(evt);
            }
        });

        CrustComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thin", "Deep", "Stuffed" }));
        CrustComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrustComboBoxActionPerformed(evt);
            }
        });

        SauceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tomato", "Pesto" }));
        SauceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SauceComboBoxActionPerformed(evt);
            }
        });

        T1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Olives", "Extra_Cheese", "Chilli", "Pepperoni", "Mushroom", "Rocket", "Jalapenos", "Onion", "Anchovy" }));
        T1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ComboBoxActionPerformed(evt);
            }
        });

        T2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Olives", "Extra_Cheese", "Chilli", "Pepperoni", "Mushroom", "Rocket", "Jalapenos", "Onion", "Anchovy" }));
        T2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ComboBoxActionPerformed(evt);
            }
        });

        Counter.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrevPizzaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Counter, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextPizzaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OkButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(T2ComboBox, 0, 190, Short.MAX_VALUE)
                            .addComponent(T1ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SauceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CrustComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SizeComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SizeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CrustComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SauceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrevPizzaButton)
                    .addComponent(NextPizzaButton)
                    .addComponent(DeleteButton)
                    .addComponent(OkButton)
                    .addComponent(Counter))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextPizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextPizzaButtonActionPerformed
        this.pos += 1;
        if(this.pos <= (order.numOfPizzas()-1)){
            jTextArea1.setText((order.getPizza(pos).getInvoice()));
            updateBoxes();  
        }else if(this.pos > order.numOfPizzas()-1){
            this.pos -= 1;
            jTextArea1.setText((order.getPizza(pos).getInvoice()));
            updateBoxes(); 
        }
        Counter.setText(String.valueOf(this.pos+1));
    }//GEN-LAST:event_NextPizzaButtonActionPerformed
    
    public void updateBoxes(){
        Pizza temp = order.getPizza(pos);
        SizeComboBox1.setSelectedItem(temp.getSize());
        CrustComboBox.setSelectedItem(temp.getCrust());
        SauceComboBox.setSelectedItem(temp.getSauce());
        T1ComboBox.setSelectedItem(temp.getTopping1());
        T2ComboBox.setSelectedItem(temp.getTopping2());
    }
    
    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        orderForm frame = new orderForm(this.order); 
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(orderForm.EXIT_ON_CLOSE); 
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    private void PrevPizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevPizzaButtonActionPerformed
        this.pos -= 1;
        if(this.pos >= 0){
            jTextArea1.setText((order.getPizza(pos).getInvoice()));
            updateBoxes();  
        }else{
            this.pos += 1;
            jTextArea1.setText((order.getPizza(pos).getInvoice()));
            updateBoxes(); 
        }
        Counter.setText(String.valueOf(this.pos+1));
    }//GEN-LAST:event_PrevPizzaButtonActionPerformed
    
    private void update(){
        order.updatePizza(
                SizeComboBox1.getSelectedItem().toString(), 
                CrustComboBox.getSelectedItem().toString(),
                SauceComboBox.getSelectedItem().toString(),
                T1ComboBox.getSelectedItem().toString(),
                T2ComboBox.getSelectedItem().toString(),
                this.pos
                );
        jTextArea1.setText((order.getPizza(pos).getInvoice()));
    }
    
    private void SizeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeComboBox1ActionPerformed
        update();
    }//GEN-LAST:event_SizeComboBox1ActionPerformed

    private void CrustComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrustComboBoxActionPerformed
        update();
    }//GEN-LAST:event_CrustComboBoxActionPerformed

    private void SauceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SauceComboBoxActionPerformed
        update();
    }//GEN-LAST:event_SauceComboBoxActionPerformed

    private void T1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ComboBoxActionPerformed
        update();
    }//GEN-LAST:event_T1ComboBoxActionPerformed

    private void T2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ComboBoxActionPerformed
        update();
    }//GEN-LAST:event_T2ComboBoxActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        order.deletePizza(this.pos);
        this.pos -= 1;
        if (this.pos < 0){
            orderForm frame = new orderForm(this.order); 
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(orderForm.EXIT_ON_CLOSE); 
            frame.setVisible(true);
            dispose();
        }else{
            jTextArea1.setText((order.getPizza(pos).getInvoice()));
            updateBoxes();
            Counter.setText(String.valueOf(this.pos+1));
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOrderFrame(order).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Counter;
    private javax.swing.JComboBox<String> CrustComboBox;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton NextPizzaButton;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton PrevPizzaButton;
    private javax.swing.JComboBox<String> SauceComboBox;
    private javax.swing.JComboBox<String> SizeComboBox1;
    private javax.swing.JComboBox<String> T1ComboBox;
    private javax.swing.JComboBox<String> T2ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
